alertmanager:
  enabled: false

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

grafana:
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 1d
    retentionSize: "500MB"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
